### ISSUE TITLE
Convert simula-rasa to TypeScript.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/simula-rasa#21]
When new PhET repo `center-and-spread` was created, I noticed that it contained a mix of .js and .ts files.  The .js files were presumably from simula-rasa, as the result of running `grunt create-sim`.    Since new sims will presumably be written in TypeScript, converting simula-rasa to TypeScript seems like the right thing to do for the PhET team.

But I'm not so sure about what's right for 3rd parties. If simula-rasa is in TypeScript, 3rd parties will be forced to write TypeScript, or (possible, but unlikely) convert what's generated by `grunt create-sim` to JavaScript. That raises an already-high bar a bit higher.  Let's discuss the 3rd-party aspect at developer meeting before I proceed.

**Comment by pixelzoom** [comment]
My feeling is that we should convert to TypeScript.  Since the (eventual) goal is to convert much (all?) common code to TypeScript, 3rd parties will need to be familiar with TypeScript to be productive.  So they might as well be writing their sims in TypeScript.

**Comment by zepumph** [comment]
>That raises an already-high bar a bit higher.

I am definitely in agreement about this, and I've talked to @chrisklus about this exact thing. That said, simula-rasa doesn't seem like the example-hill to die on for this point. If we actually wanted to lower the barrier to entry for phet-sim development, it isn't simply a matter of not using Typescript. I'm adding a thumbs up to the above bullet.

**Comment by pixelzoom** [comment]
On 2/8/22 in Slack dev-public channel, I said:
> Instead of spending time in developer meeting… If anyone has input on the conversion of simula-rasa to TypeScript, please add your comments to https://github.com/phetsims/simula-rasa/issues/21 before this Thursday’s dev meeting. If an asynchronous consensus is established, we’ll skip discussion in dev meeting.  If we don’t have a consensus, we’ll have a subgroup discussion with those devs who have commented. Thanks!

Based on the comments received, I beleive that we have a consensus, and there's no need to discuss this in dev meeting.  I'll proceed with conversion of simula-rasa to TypeScript.

**Comment by pixelzoom** [comment]
simula-rasa was converted to TypeScript in the above commit.

Tested using `grunt create-sim --repo="foo-bar" --author=CM --title="Foo Bar"`.

Note that it was necessary to temporarily add `foo-bar` to perennial-alias/data/active-repos, then restart transpile.js.  This generated files in chipper/dist/js/foo-bar, and foo-bar/foo-bar_en.html (the development HMTL file) could then be loaded in the browser.  A better solution 3rd parties will be investigated in https://github.com/phetsims/chipper/issues/1195.

@chrisklus would you mind reviewing this, since you recently reviewed another change to simula-rasa?

**Comment by chrisklus** [comment]
Apologies for the delay, will review this afternoon.

**Comment by chrisklus** [comment]
As mentioned in dev meeting, I will investigate adding TypeScript options patterns now that Screen and ScreenView have been converted to TS

**Comment by pixelzoom** [comment]
Excellent, thanks @chrisklus.  See https://github.com/phetsims/joist/issues/776#issuecomment-1041037917:

> @samreid I see that you parameterized SimulaRasaScreen and SimulaRasaScreenView, but did not convert `providedOptions` types, or change `merge` to `optionize`.   I'm still trying to wrap my head around the (complicated) `optionize` syntax.   Should `providedOptions` and `optionize` look like this? 

```ts
// SimulaRasaScreen
  constructor( providedOptions: ScreenOptions ) {
    const options = optionize<ScreenOptions, {}, ScreenOptions, 'tandem'>( {

// SimulaRasaScreenView
  constructor( model: SimulaRasaModel, providedOptions: ScreenViewOptions ) {
    const options = optionize<ScreenViewOptions, {}, ScreenViewOptions, 'tandem'>( {
```

So you might be able to just use these, but I'm not 100% certain.

**Comment by chrisklus** [comment]
In the above commits, I:

* removed function visibility annotations in JSDocs
*  removed JSDocs that had no parameter descriptions. @pixelzoom and I discussed this, and it sounds like he keeps them around for constructors sometimes, but we don't have it listed as a TS convention, so agreed they were okay to remove.
* added return types to class functions
* added visibility annotations to class functions. @pixelzoom and I discussed this and decided to add them because we both prefer, but since this convention is developer preference, they can easily be removed for new sims if desired.
* converted options to use optionize in the way proposed by @pixelzoom in https://github.com/phetsims/simula-rasa/issues/21#issuecomment-1043354892 (see https://github.com/phetsims/simula-rasa/commit/176867a6fe8a045ecd469c2e1006535da6cd7ca4), BUT...

...then when testing a new sim, it was confusing to me that tandems are used everywhere, but were only technically required by TypeScript for the model, not the screen view or screen. But I realized to make that consistent, more SimulaRasa-specific options types would need to be added, even though it feels like the options pattern should indeed look like https://github.com/phetsims/simula-rasa/issues/21#issuecomment-1043354892 and not add more boilerplate since simula-rasa is like the default state of a sim. To do that and have correct typing for tandem, that either means removing phet-io entirely from simula-rasa or making tandem required by TS in Screen.ts and ScreenView.ts. But the latter would mean that all sims in TypeScript would need basic tandems for their top level files, and I'm guessing we're not ready for that.

So I asked for a recommendation from @samreid and we decided on opening a new issue (https://github.com/phetsims/simula-rasa/issues/23) for developer discussion regarding phet-io in simula-rasa/all sims, but for now went for consistency and made tandem also required in SimulaRasaScreen and SimulaRasaScreenView in https://github.com/phetsims/simula-rasa/commit/0587373eefcb32c364290c26001af7cb8d655145.

@pixelzoom reviewed all changes with me over zoom except the change from the paragraph above, but it is working well in testing. I tested creating a sim with `grunt create-sim --repo=test-sim --name="Test Sim" --author="CK"` and all seems well. Closing here, and will continue discussion in #23.
